language: ruby

rvm:
- 2.5.0

before_install:
- gem update --system
- gem install bundler
services:
- postgresql

before_script:
- psql -c 'create database pgapp_test;' -U postgres

deploy:
  provider: heroku
  api_key:
    secure: IwIBnnNN+2Eql8PtCYP/j+MDj5/bPzJyxtEZK5Vtr3hYjc/9R0KD6uxpM06W/82J5QvVXjnOiTIUv/FDPgdiSeCfLRuXPBUaCZJ18413DLz8yWwsj4lM656nzJh2K4Jg8aNjFkT9Gke7YmqguieFzVFtbtBHjmLDeR/DChZHT0quNV9JpakrJIvfpmD/CpNHGVyHLKt5MNhlPyakzrSDor3NsZSHV9OOYsRZuhyre5r3wSNdB1iPfBkdAtxQc0ySgC00wYV2XVdo4gTmarPp73G3dbq84QmAOl/xbZCvaaS0tDGNVXpGhwA2V773FAJBJS69hNmgzmg1ut/ZHCQ6RdgBpCu4XCeij3AdEkP/+uS98i0TeI+TgPY32WGc20NJjIbDB9fm2gCGW6y8KSv83QJNCPPKJ2xKO6sCI9OE/BbOnParrEFB+zn5uPp5hfM7fno7wSDOCGRnU62ASkc75cjYpUaHPEpC5lhb2CmYc2pYT0AbBDElrnkmnNcVSmOwU0C/xlSWd5G2BtjukGyZOFPSNu8f3Y8pkUMJI27FMvKU3iVjHmWEDO0zs7rugHyLxC+0YhRUkIlhUb8ZELr97uSI0EPKm/M2iyqxWgxno4MTxJ0D6w7YV+7nRQ89rR6B7Gl3C8b66vKZxD70dyURPN9+T+5Z1COstvAt8TeSh54=
  app: Acebook
  on: 
    repo: lucianmot/acebook-off-the-rails
